### ISSUE TITLE
Strange error when JSON is invalid

### ISSUE THREAD

**Issue by jayvdb** [Badgerati/Fudge#43]
Leave out a comma and the error is `Invalid JSON primitive: .` .  It would be nice if there was an indication which line the error was on, or just say "`Invalid JSON: <filename>`" or something like that.

**Comment by Badgerati** [comment]
Hey! And wow!

So this error is thrown by PowerShell's `ConvertFrom-Json`. There is a an error that should get thrown after that which is close to your "`Invalid JSON: <filename>`", but I'm guessing the main function throws first.

Also just gonna mention that I have seen all these issues! Currently I'm hard at work over on [Pode](https://github.com/Badgerati/Pode), but I'll try and deal with these, too - there's a few things I wouldn't mind changing.

**Comment by jayvdb** [comment]
Oh, I missed your response 12 days ago.  I did see you were active elsewhere, so guessed you'd be back when you could.

You can see your baby in action at https://ci.appveyor.com/project/jayvdb/package-manager/history and https://ci.appveyor.com/project/jayvdb/coala-bears/history and https://travis-ci.org/jayvdb/coala-bears/jobs/547486574 - PRs about to land soon in 10+ @coala repos using Fudge + @moremoban to have a single WinOps/CI scripts for AppVeyor & Travis CI ([Win](https://docs.travis-ci.com/user/reference/windows/)), and hopefully also Windows users install locally with the same scripts.  After that, you will have @coala as users, and probably helping with dev too.

**Comment by jayvdb** [comment]
https://gitlab.com/coala/mobans/merge_requests/130 created as the first of many MRs.

**Comment by Badgerati** [comment]
That's awesome! It's similar to how we have a few systems where I work being setup 😄
