### ISSUE TITLE
which command relies on PATH

### ISSUE THREAD

**Issue by jayvdb** [Badgerati/Fudge#45]
The which command relies on the program being findable using PATH, like `where.exe`.

This means it does not work after `fudge install` in a `cmd.exe` , until the `$env:PATH` has been refreshed from the registry, e.g. using https://github.com/chocolatey-archive/chocolatey/blob/master/src/redirects/RefreshEnv.cmd from cmd or https://github.com/chocolatey/choco/blob/stable/src/chocolatey.resources/helpers/functions/Update-SessionEnvironment.ps1 in powershell.

It would be helpful if it also searched for the program using the PATH live in the registry keys, or invoked `Update-SessionEnvironment` before looking for programs.

**Comment by Badgerati** [comment]
I've often found that `RefreshEnv.cmd` and `Update-SessionEnvironment` don't always work for some reason. But then when you run a similar script to what `Update-SessionEnvironment` does it works 🤔.

I think for this it might be better having an inbuilt function to refresh the current PATH after each package, especially if we do #53 - as it could mean people use Fudge for solely PowerShell Gallery, and don't have Chocolatey installed.

**Comment by jayvdb** [comment]
Maybe a separate project for RefreshEnv.* ? or even an org with projects per language c.f. https://github.com/chocolatey/choco/issues/1851

**Comment by jayvdb** [comment]
While a local function may be useful long term, it is important to not copy and paste Choco functions here as they are Apache 2.0 licensed.  If there are problems with the Choco function, ti is best to find and describe them, and that then gives a good basis for creating a new function which is clearly a new implementation that can be MIT licensed.

**Comment by jayvdb** [comment]
One obvious difference, which could lead to a different algorithm, is that `which` only needs the `PATH` to be refreshed, not the entire `$env` , and it only needs to be refreshed if there are new entries.

Also a new implementation can be more careful about what is is changing, comparing the User and Machine registry and `$env:PATH`, and only update the `$env:PATH` if there are *new* entries in User and Machine registries.  i.e. dont remove items from `$env:PATH`.

e.g. if I do `$ PATH=$PATH:~/.local/bin powershell -c "fudge which php"` , I do not expect that `~/.local/bin` will be discarded.  Currently the choco `Update-SessionEnvironment` discards any custom items in $env:PATH .  This also affects hooks, because often I want a hook to do something like  `$env:PATH = ($env:PATH + ';' + $new_location)` , but if choco functions are called again in the same session, and one of them uses `Update-SessionEnvironment`, the addition of `$new_location` disappears, and oh my that has caused me to scratch my head for a while wondering why the `PATH` doesnt have the item I very clearly added.

**Comment by Badgerati** [comment]
The PATH only adding new entries is good; but I think leaving in refreshing all other environment variables is good - as Java can adding new entries like JAVA_HOME that could be needed 🤔

**Comment by jayvdb** [comment]
> but I think leaving in refreshing all other environment variables is good ..

sure, useful, but not needed for `which`.

When rewriting code under a new license, build each piece slowly and differently to avoid any doubt it is a new creativity.

**Comment by Badgerati** [comment]
The idea was putting the refresh after each package install/uninstall - as that will fix `which` and `install` in one go.

But, I can split the function out into two - one for all variables (except PATH), and one for PATH. only Both are called after each package, and only PATH is called within `which` for any software installed outside of Fudge.

**Comment by jayvdb** [comment]
The point I am making is about copyright.  It is a very large non-technical problem.  The commit history needs to obviously show that Apache code wasnt copied, otherwise this project becomes unusable.

**Comment by Badgerati** [comment]
In that case I can recreate the branch, remove the references, and do it again - splitting it out as stated above.
