### ISSUE TITLE
Allow fudge install -args

### ISSUE THREAD

**Issue by jayvdb** [Badgerati/Fudge#47]
When `fudge install` is called without naming packages, the switch `-args` is silently ignored.

There are args which are suitable to be used for all packages, such as `--forcex86` for creating a x86 setup when that isnt normally wanted and shouldnt be put into the Fudgefile.

i.e. I want my CI to have a --forcex86 job, but not force that onto the devs by putting it into the `Fudgefile`.

**Comment by Badgerati** [comment]
Ooops, like was likely an oversight at the time! 🙈
