### ISSUE TITLE
Show version installed instead of "latest"

### ISSUE THREAD

**Issue by jayvdb** [Badgerati/Fudge#49]
After the installation is done for an unspecified version, fudge should show which version was installed.

**Comment by Badgerati** [comment]
Instead of showing:

```
> Installing curl (latest) > installed
```

it'll now show:

```
> Installing curl (7.65.1) > installed
```

**Comment by jayvdb** [comment]
That output seems to be identical to how it would look if a version was specified in the Fudgefile.

I think it is useful that there is some visual distinction to indicate that the version isnt pinned and it is searching for, and using, the latest.

I am also interested in how this looks when combined with `Upgrading ...` lines , and lines where no upgrade is needed.

**Comment by jayvdb** [comment]
Another aspect to the installation UI is that it would be helpful to see which *extra* packages (and their versions) were installed for each Fudgefile entry.  That doesnt need to be included in this fix, but it is worth considering how the UI should report multiple packages per Fudgefile entry.

e.g. if Fudge was tracking the dependencies as they are being installed, parsing the choco log which does messily give the dependencies in order they are installed.

Should it look like this?  doing steps

    Installing curl (7.65.1) > installed 7z.portable (1.2.3)
                             > installed

or as a tree, and then marking the top of the tree "installed" after completion.

    Installing curl (7.65.1) > installed
    + installed 7z.portable (1.2.3)

the latter is harder to do with curses, but still possible .. not sure about PS console UI libraries.

**Comment by Badgerati** [comment]
> That output seems to be identical to how it would look if a version was specified in the Fudgefile.

I could make it the following instead?

```
> Installing curl (latest [7.65.1]) > installed
```

> e.g. if Fudge was tracking the dependencies as they are being installed, parsing the choco log which does messily give the dependencies in order they are installed.

For this, I prefer the latter syntax. The only issue I can see is that Fudge won't have the whole choco output until the very end. This means any dependency packages installed can only be parsed and shown at the end.

But I do agree that the this it likely better as a different feature to be raised.

**Comment by jayvdb** [comment]
> Installing curl (latest [7.65.1]) > installed

That looks good.
