### ISSUE TITLE
Retry choco installs which timeout

### ISSUE THREAD

**Issue by jayvdb** [Badgerati/Fudge#51]
It would be helpful if Fudge detected nuget/choco failed due to transient network problems, and retried the operation.

i.e. workaround upstream issues https://github.com/chocolatey/choco/issues/1853 and https://github.com/NuGet/Home/issues/2269

**Comment by Badgerati** [comment]
We suffer this one a fair bit where I work - as we run an in-house Chocolatey server that's very under-powered 😕 . Fortunately we have Chef retry a few times, but it would be nice to have Fudge do it itself.

As you point out in https://github.com/chocolatey/choco/issues/1853, the error message is always `the operation has timed out`.

So we could make it that if Fudge detects the timeout, it sleeps for a few seconds and then retries - up to 3 times - before failing.
